# The name of the work flow. Badges will use this name
name: Check files

on:
  push:
    branches: 
    - main

jobs:
  analysis:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Expand-Archive
      id: unpack
      run: |
        Expand-Archive archive/net472.zip -DestinationPath .\